# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-27 22:30
from __future__ import unicode_literals

from django.db import migrations

from ..utils import ensure_permissions


def update_default_groups(apps, schema_editor):
    """
    Update default groups and their permissions.
    """
    # Get models
    # Note: We can't import the models directly as they may be a newer
    # version than this migration expects
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')
    ResourceProjectAssignment = apps.get_model('deployment', 'ResourceProjectAssignment')

    # Get HR+PMGT groups
    hr = Group.objects.get_or_create(name='Human Resources')[0]
    pmgt = Group.objects.get_or_create(name='Project Management')[0]

    # HR can add/modify/issue assignments, PMGT can review them
    hr.permissions.add(*ensure_permissions(ResourceProjectAssignment, ['add', 'change', 'issue'],
                                           permission_model=Permission))
    pmgt.permissions.add(*ensure_permissions(ResourceProjectAssignment, ['review'],
                                             permission_model=Permission))


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20160618_1521'),
        ('deployment', '0006_resourceprojectassignment_resourceprojectassignmentaction'),
    ]

    operations = [
        migrations.RunPython(update_default_groups)
    ]
