# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-18 15:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('deployment', '0004_worklog_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheet',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='timesheetaction',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
