# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-24 20:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0002_auto_20160618_1500'),
        ('accounts', '0005_update_defaults'),
        ('work', '0006_auto_20160724_2011'),
        ('resources', '0006_remove_resource_project'),
        ('deployment', '0007_presence'),
        ('organizations', '0003_auto_20160517_0222'),
    ]

    operations = [
        migrations.AddField(
            model_name='worklog',
            name='activity_base',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='work.ActivityBase'),
        ),
        migrations.AlterField(
            model_name='worklog',
            name='activity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='work.Activity'),
        ),
        migrations.AddField(
            model_name='presence',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='resources.ResourceCategory'),
        ),
        migrations.AddField(
            model_name='presence',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.Company'),
        ),
        migrations.AddField(
            model_name='presence',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organizations.Department'),
        ),
        migrations.AddField(
            model_name='presence',
            name='equipment_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='resources.EquipmentType'),
        ),
        migrations.AddField(
            model_name='presence',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='geo.Location'),
        ),
        migrations.AddField(
            model_name='presence',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Account'),
        ),
        migrations.AddField(
            model_name='presence',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organizations.Position'),
        ),
        migrations.AddField(
            model_name='presence',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.Resource'),
        ),
        migrations.AddField(
            model_name='presence',
            name='timesheet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deployment.TimeSheet'),
        ),
        migrations.AddField(
            model_name='worklog',
            name='presence',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='work_logs', to='deployment.Presence'),
        ),
        migrations.AlterUniqueTogether(
            name='presence',
            unique_together=set([('timesheet', 'resource')]),
        ),
    ]
