# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-24 20:25
from __future__ import unicode_literals

from django.db import migrations


def set_work_logs_presence(apps, schema_editor):
    """
    Set WorkLog presence value for all work log that haven't one set already.
    """
    # Get models
    # Note: We can't import the models directly as they may be a newer
    # version than this migration expects
    Presence = apps.get_model('deployment', 'Presence')
    WorkLog = apps.get_model('deployment', 'WorkLog')

    # Get all presence groups from work logs without presences
    rows = WorkLog.objects.filter(
        presence__isnull=True
    ).values(
        'timesheet',
        'resource',
        'company',
        'category',
        'location',
        'department',
        'position',
        'equipment_type'
    )

    # Create and set presence instance for each group
    for row in rows:
        # Generate de-normalized resource data (stored in presence)
        timesheet_id = row.pop('timesheet_id')
        resource_id = row.pop('resource_id')

        # Upsert presence instance
        presence = Presence.objects.update_or_create(
            row,
            timesheet=timesheet_id,
            resource=resource_id
        )[0]

        # Set presence in work logs
        WorkLog.objects.filter(
            timesheet=timesheet_id,
            resource=resource_id
        ).update(
            presence=presence
        )


class Migration(migrations.Migration):

    dependencies = [
        ('deployment', '0008_auto_20160724_2011'),
    ]

    operations = [
        migrations.RunPython(set_work_logs_presence)
    ]
