# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-24 21:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deployment', '0009_auto_20160724_2025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worklog',
            name='activity',
        ),
        migrations.RemoveField(
            model_name='worklog',
            name='category',
        ),
        migrations.RemoveField(
            model_name='worklog',
            name='company',
        ),
        migrations.RemoveField(
            model_name='worklog',
            name='department',
        ),
        migrations.RemoveField(
            model_name='worklog',
            name='equipment_type',
        ),
        migrations.RemoveField(
            model_name='worklog',
            name='location',
        ),
        migrations.RemoveField(
            model_name='worklog',
            name='position',
        ),
        migrations.RemoveField(
            model_name='worklog',
            name='resource',
        ),
        migrations.RemoveField(
            model_name='worklog',
            name='timesheet',
        ),
        migrations.AlterField(
            model_name='worklog',
            name='activity_base',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='work.ActivityBase'),
        ),
        migrations.AlterField(
            model_name='worklog',
            name='presence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_logs', to='deployment.Presence'),
        ),
    ]
