# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-28 11:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0005_auto_20160423_1943'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='project',
        ),
    ]
