# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-28 11:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('work', '0003_auto_20160517_0222'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='managers',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
