# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-02 20:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0004_project_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='managers',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
