# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-24 20:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_update_defaults'),
        ('work', '0005_auto_20160702_2027'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('code', models.CharField(max_length=6)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Inactivity',
            fields=[
                ('base', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='work.ActivityBase')),
                ('type', models.CharField(choices=[('P', 'Personal'), ('E', 'External')], max_length=1)),
            ],
            options={
                'abstract': False,
            },
            bases=('work.activitybase',),
        ),
        migrations.AddField(
            model_name='activitybase',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Account'),
        ),
        migrations.AddField(
            model_name='activity',
            name='base',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='work.ActivityBase'),
        ),
    ]
