# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-24 20:26
from __future__ import unicode_literals

from django.db import migrations


def set_activities_base(apps, schema_editor):
    """
    Set Activity base value for all activities that haven't one set already.
    """
    # Get models
    # Note: We can't import the models directly as they may be a newer
    # version than this migration expects
    ActivityBase = apps.get_model('work', 'ActivityBase')
    Activity = apps.get_model('work', 'Activity')

    # Get all activities without parent (base)
    activities = Activity.objects.filter(base__isnull=True)

    # Create and set base for each
    for activity in activities:
        activity.base = ActivityBase.objects.create(
            name=activity.name,
            code=activity.code
        )
        activity.save()


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0006_auto_20160724_2011'),
    ]

    operations = [
        migrations.RunPython(set_activities_base)
    ]
