# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-24 21:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0007_auto_20160724_2026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='code',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='id',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='name',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='owner',
        ),
        migrations.AlterField(
            model_name='activity',
            name='base',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='work.ActivityBase'),
        ),
    ]
